### PR TITLE
rescue unknown thread id

### PR DESCRIPTION
**Pull request by jackfan108**
James and I tested our new lhm solution and failed the first time but succeeded the second time.
It was failing on errors such as `Mysql2::Error: Unknown thread id: 1020918: KILL 1020918;` We should rescue that error since it’s a simple race condition(process(query) finishing before kill command goes through). Quick googling did not result in syntax such as `kill $process_id if $process_id exist` --> which means rescuing that error seems like the way to go for now.

### CODE REVIEW

**Review by goodgravy — APPROVED** [review]
I'm assuming this is SUPER difficult to test?

If you've thought about it and it's incredibly challenging I'm a reluctant 👍.

If you think there's a way to test, let's add that.

**Comment by jackfan108** [comment]
yeah @goodgravy I can't think of an easy way to test this. I'd like to ship this and test in prod. This is something that's **not** gonna change that often, so I'm feeling towards "if it works in prod I'm okay with it"

**Comment by goodgravy** [comment]
Gotcha, OK—👍 in that case

**Comment by jackfan108** [comment]
@goodgravy local entangler integration spec passing, merging this!

**Pull request merged**
